### ISSUE TITLE
Pyecharts not displaying in Jupyter Notebooks even though they do in Jupyter Lab

### ISSUE THREAD

**Issue by AdrianAntico** [pyecharts/pyecharts#2301]
**问题**
How can I get a pyechart to display in a jupyter notebook? I can get it to display in a jupyter lab instance by following the examples on the page: https://pyecharts.org/#/en-us/notebook. I just installed Jupyter Notebooks and Jupyter Labs yesterday. I made no adjustments to either (not sure if you can). Is there something I need to tweak in the Jupyter Notebooks to enable the display of pyecharts?

**运行环境（系统环境及 pyecharts 版本）**
Windows 10, chrome browser, python 3.11, pyecharts version 2.0.5

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/42076988/57bd36ac-51e9-45ae-a78c-2f7852915c32)

**Comment by sunhailin-Leo** [comment]
@AdrianAntico 
* Is it possible to check your browser console? Maybe the error message is in there, and please provide the version of jupyter you are currently using.

**Comment by AdrianAntico** [comment]
@sunhailin-Leo here's a screenshot of the jupyter --version

Also, it appears that if I utilize the same code as for Jupyter Lab then the plots appear in Jupyter Notebooks. That is, if I specify CurrentConfig.Render_TYPE = 'jupyter_lab', utilize load_javascript() and then in the following cell render_notebook(), the plots do show up. Is that supposed to work? Because the pyecharts jupyter notebook example provided doesn't call any of those...

![image](https://github.com/pyecharts/pyecharts/assets/42076988/ebeb6870-40ad-473d-9e2c-7d92622b07d7)

**Comment by sunhailin-Leo** [comment]
@AdrianAntico 
* If you start jupyter with a command like `jupyterlab...` , then you're using jupyterlab, or if you can see `/lab` in your browser address bar, switching to `/tree` is traditional notebook mode.
* In general for rendering problems in Jupyter you can try to plot in different modes (jupyterlab or jupyter notebook). The reason for this is that older versions of Jupyter had a larger distinction between lab and notebook, but this has been slowly reduced since the new version.
